### ISSUE TITLE
The error 403 when calling an API using Java language translates to "Forbidden".

### ISSUE THREAD

**Issue by Jennifer-sys** [cohere-ai/cohere-java#29]
Hello, I'm a Java development engineer, and I've been encountering issues with using cohere（https://api.cohere.com/v1/rerank）. Specifically, I'm getting a 403 error when calling an API interface, even though I'm able to successfully call it using Postman. Could you please help me troubleshoot this issue?

**Comment by billytrend-cohere** [comment]
Please could you share a code snippet?

**Comment by Jennifer-sys** [comment]
Hello, thank you very much for your reply. Actually, the code I'm using for [cohere-java] is very simple. I'm just running your sample code. Here's a screenshot from my side.
**postman request：**
![image](https://github.com/user-attachments/assets/6b3b0c10-a2c6-4125-97e8-3a476c575c0a)

**java-api：**
![image](https://github.com/user-attachments/assets/b75955fe-a165-42f2-ac2a-1e480f5b9775)
![image](https://github.com/user-attachments/assets/b4632241-2824-4d5d-8950-70255008f3e4)
